enable some terraform scripts

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -111,101 +111,101 @@ jobs:
       #     #   --extra-vars hello=there
       #     #   --verbose
 
-  # terraform:
-  #   name: "execute terraform project"
-  #   runs-on: ubuntu-latest
-  #   if: ${{ always() }}
-  #   needs:
-        # - ansible
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #       working-directory: ./terraform
+  terraform:
+    name: "execute terraform project"
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs:
+      - ansible
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform
 
-  #   steps:
-  #     - name: Checkout the repository to the runner
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout the repository to the runner
+        uses: actions/checkout@v3
 
-  #     - name: Set up Python 3.8
-  #       uses: actions/setup-python@v4
-  #       with:
-  #         python-version: 3.8
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
 
-  #     - name: Setup Terraform with specified version on the runner
-  #       uses: hashicorp/setup-terraform@v2
-  #       with:
-  #         terraform_version: 1.3.0
+      - name: Setup Terraform with specified version on the runner
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.3.0
 
-  #     - name: Setup SOPS with binary installer
-  #       uses: mdgreenwald/mozilla-sops-action@v1.4.1
+      - name: Setup SOPS with binary installer
+        uses: mdgreenwald/mozilla-sops-action@v1.4.1
 
-  #     - name: Decrypt Terraform backend configuration with SOPS
-  #       run: sops --decrypt backend.conf.enc > backend.conf
-  #       env:
-  #         SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
+      - name: Decrypt Terraform backend configuration with SOPS
+        run: sops --decrypt backend.conf.enc > backend.conf
+        env:
+          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
 
-  #     - name: Configure aws credentials
-  #       uses: aws-actions/configure-aws-credentials@v2
-  #       with:
-  #         role-to-assume: arn:aws:iam::433082585283:role/github-oidc-terraform
-  #         role-session-name: proxmox-cluster-pineapple
-  #         aws-region: "eu-central-1" # ${{ env.AWS_REGION }}
+      - name: Configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::433082585283:role/github-oidc-terraform
+          role-session-name: proxmox-cluster-pineapple
+          aws-region: "eu-central-1" # ${{ env.AWS_REGION }}
 
-  #     - name: Terraform init
-  #       id: init
-  #       run: terraform init -backend-config=backend.conf
+      - name: Terraform init
+        id: init
+        run: terraform init -backend-config=backend.conf
 
-  #     - name: Terraform format
-  #       id: fmt
-  #       run: terraform fmt -check
+      - name: Terraform format
+        id: fmt
+        run: terraform fmt -check
 
-  #     - name: Terraform validate
-  #       id: validate
-  #       run: terraform validate
+      - name: Terraform validate
+        id: validate
+        run: terraform validate
 
-  #     - name: Terraform scanning with checkov
-  #       uses: bridgecrewio/checkov-action@master
-  #       with:
-  #         directory: ./terraform
-  #         framework: terraform
+      - name: Terraform scanning with checkov
+        uses: bridgecrewio/checkov-action@master
+        with:
+          directory: ./terraform
+          framework: terraform
 
-  #     - name: Terraform plan
-  #       id: plan
-  #       if: github.event_name == 'pull_request'
-  #       run: terraform plan -no-color -input=false
-  #       continue-on-error: true
+      # - name: Terraform plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
 
-  #     - uses: actions/github-script@v6
-  #       if: github.event_name == 'pull_request'
-  #       env:
-  #         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-  #       with:
-  #         script: |
-  #           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-  #           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-  #           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-  #           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      # - uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-  #           <details><summary>Show Plan</summary>
+      #       <details><summary>Show Plan</summary>
 
-  #           \`\`\`\n
-  #           ${process.env.PLAN}
-  #           \`\`\`
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
 
-  #           </details>
-  #           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       </details>
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-  #           github.rest.issues.createComment({
-  #             issue_number: context.issue.number,
-  #             owner: context.repo.owner,
-  #             repo: context.repo.repo,
-  #             body: output
-  #           })
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-  #     - name: Terraform Plan Status
-  #       if: steps.plan.outcome == 'failure'
-  #       run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-  #     - name: Terraform Apply
-  #       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-  #       run: terraform apply -auto-approve -input=false
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false
